sudo: required
dist: trusty
language: generic
cache:
  - apt
  - ccache
virtualenv:
  system_site_packages: true
git:
  submodules: false

env:
  global:
  - TERM=dumb # Reduce logfile length by not logging build script download progress

before_install:
  - sudo add-apt-repository -y ppa:v-launchpad-jochen-sprickerhof-de/pcl
  - sudo apt-get update -qq && sudo apt-get install -qq -y build-essential cmake debhelper freeglut3-dev gtk-doc-tools libboost-filesystem-dev libboost-iostreams-dev libboost-program-options-dev libboost-random-dev libboost-regex-dev libboost-signals-dev libboost-system-dev libboost-thread-dev libcurl4-openssl-dev libfreeimage-dev libglew-dev libgtkmm-2.4-dev libltdl-dev libgsl0-dev libportmidi-dev libprotobuf-dev libprotoc-dev libqt4-dev libqwt-dev libtar-dev libtbb-dev libtinyxml-dev libxml2-dev ncurses-dev pkg-config protobuf-compiler python-matplotlib libvtk5.8 libvtk5-dev libvtk5-qt4-dev libqhull-dev python-pygame doxygen mercurial libglib2.0-dev openjdk-6-jdk python-dev gfortran f2c libf2c2-dev spacenavd libspnav-dev python-numpy python-scipy python-yaml python-vtk python-pip libgmp3-dev libblas-dev liblapack-dev libv4l-dev subversion libxmu-dev libusb-1.0-0-dev python-pymodbus graphviz curl libwww-perl libterm-readkey-perl libx264-dev libopenni-dev swig wget libqglviewer-dev libpcl-1.7-all libdc1394-22-dev libsuitesparse-dev libsdl1.2-dev xvfb texlive-base > /dev/null 2>&1
  - cmake --version
  - wget http://terminator.robots.inf.ed.ac.uk/public/opencv_2.4.12.2.deb > /dev/null 2>&1
  - sudo dpkg -i opencv_2.4.12.2.deb && sudo ldconfig
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0 ; fi
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16
  - cd $TRAVIS_BUILD_DIR
  - sed -i 's/git@github.com:/https:\/\/github.com\//g' $TRAVIS_BUILD_DIR/.gitmodules
  - sed -i 's/git@github.com:/https:\/\/github.com\//g' $TRAVIS_BUILD_DIR/catkin_ws/.gitmodules
  - sed -i 's/ssh:\/\/git@github.com\//https:\/\/github.com\//g' $TRAVIS_BUILD_DIR/software/externals/cmake/externals.cmake
  - git config --global user.email "builds@travis-ci.com" && git config --global user.name "Travis CI"
  - git submodule deinit -f catkin_ws/src/exotica-dev && rm -rf catkin_ws/src/exotica-dev
  - git add .gitmodules catkin_ws/.gitmodules software/externals/cmake/externals.cmake
  - git rm --cached -f catkin_ws/src/exotica-dev
  - git submodule update --init --recursive
  - cd $TRAVIS_BUILD_DIR/software/director && git remote add sandbox https://github.com/openhumanoids/director.git && git fetch sandbox

install: true

script:
  - cd $TRAVIS_BUILD_DIR/software
  - source $TRAVIS_BUILD_DIR/software/config/drc_environment.sh
  - mkdir $TRAVIS_BUILD_DIR/software/externals/pod-build
  - cd $TRAVIS_BUILD_DIR/software/externals/pod-build
  - cmake .. -DBUILD_PRIVATE_EXTERNALS:BOOL=OFF -DUSE_SYSTEM_LCM:BOOL=OFF -DCMAKE_INSTALL_PREFIX:STRING=$TRAVIS_BUILD_DIR/software/build -DUSE_SYSTEM_PCL:BOOL=ON -DUSE_SYSTEM_OPENCV:BOOL=ON
  - cd $TRAVIS_BUILD_DIR/software/externals
  - make -j4 -Wno-dev > ~/build_log_externals.txt # turn off CMake policy warnings
  - cd $TRAVIS_BUILD_DIR/software
  - cd drake/drake
  - make -j1 -Wno-dev
  - cd ../..
  - make -j4 -Wno-dev
  #- cd .. && ./.ci_testing.sh

