robot_1:
  urdf: "/software/perception/manipulation_tracking/urdf/irb140_chull_ati_gelsight.urdf"
  channel: "EST_MANIPULAND_STATE_IRB140_ATI_GELSIGHT"
  gt_channel: "EST_MANIPULAND_STATE_IRB140_ATI_GELSIGHT_GT"
  link: "link_5"

robot_2:
  urdf: "/software/perception/manipulation_tracking/urdf/optotrak_cube.urdf"
  channel: "EST_MANIPULAND_STATE_optotrak_cube"
  gt_channel: "EST_MANIPULAND_STATE_optotrak_cube_GT"
  link: "optotrak_cube"
  offset: [0, -0.06305, 0.06305]

relative_transform: [0, 0, 0, 90, 0, 0]