robots:
  irb140:
    urdf: "/software/models/IRB140/urdf/irb_140_ati_schunk_gelsight.urdf"
    q0:
      base_x: -0.17
      base_z: 0.911
  #bolt:
  #  urdf: "/software/perception/manipulation_tracking/urdf/tiny_bolt.urdf"
  #  q0:
  #    base_x: 0.52
  #    base_y: 0.13
  #    base_z: 0.70
  #    base_roll: 0.0
  hole_box:
    urdf: "/software/perception/manipulation_tracking/urdf/hole_box.urdf"
    q0:
      base_x: 0.60
      base_y: 0.10
      base_z: 0.73
      base_roll: 0.0
  tiny_screwdriver:
    urdf: "/software/perception/manipulation_tracking/urdf/tiny_screwdriver.urdf"
    q0:
      base_x: 0.57
      base_y: 0.13
      base_z: 0.8
      base_roll: 3.14
  desk:
    urdf: "/software/perception/manipulation_tracking/urdf/desk.urdf"
    q0:
      base_x: 0.61
      base_y: 0.2
      base_z: 0.7
  xtion:
    urdf: "/software/perception/manipulation_tracking/urdf/xtion.urdf"
    q0:
      base_x: 0.95
      base_y: -0.54
      base_z: 1.24
      base_roll: -2.12
      base_pitch: -0.018
      base_yaw: 0.469

robots_less_collision:
  irb140:
    urdf: "/software/models/IRB140/urdf/irb_140_ati_schunk_gelsight_less_collision.urdf"
    q0:
      base_x: -0.17
      base_z: 0.911
  #bolt:
  #  urdf: "/software/perception/manipulation_tracking/urdf/tiny_bolt.urdf"
  #  q0:
  #    base_x: 0.52
  #    base_y: 0.13
  #    base_z: 0.70
  #    base_roll: 0.0
  hole_box:
    urdf: "/software/perception/manipulation_tracking/urdf/hole_box.urdf"
    q0:
      base_x: 0.60
      base_y: 0.70
      base_z: 0.0
      base_roll: 0.0
  tiny_screwdriver:
    urdf: "/software/perception/manipulation_tracking/urdf/tiny_screwdriver.urdf"
    q0:
      base_x: 0.57
      base_y: 0.13
      base_z: 0.8
      base_roll: 3.14
  desk:
    urdf: "/software/perception/manipulation_tracking/urdf/desk.urdf"
    q0:
      base_x: 0.61
      base_y: 0.2
      base_z: 0.7
  xtion:
    urdf: "/software/perception/manipulation_tracking/urdf/xtion.urdf"
    q0:
      base_x: 0.95
      base_y: -0.54
      base_z: 1.24
      base_roll: -2.12
      base_pitch: -0.018
      base_yaw: 0.469


force_align:
  # force alignment of these frames in the estimator every iteration
  source_robot: "IRB140"
  dest_frame: "robot_base"

publish:
  irb140_state:
    robot_name: "IRB140"
    type: "state"
    channel: "EST_MANIPULAND_STATE_IRB140_ATI_GELSIGHT"
  #tiny_bolt_state:
  #  robot_name: "bolt"
  #  type: "state"
  #  channel: "EST_MANIPULAND_STATE_bolt"
  tiny_screwdriver_state:
    robot_name: "tiny_screwdriver"
    type: "state"
    channel: "EST_MANIPULAND_STATE_tiny_screwdriver"
  desk_state:
    robot_name: "desk"
    type: "state"
    channel: "EST_MANIPULAND_STATE_desk"
  hole_box_state:
    robot_name: "hole_box"
    type: "state"
    channel: "EST_MANIPULAND_STATE_hole_box"
  #xtion_state:
  #  robot_name: "xtion"
  #  type: "state"
  #  channel: "EST_MANIPULAND_STATE_xtion"
  #xtion_offset:    
  #  robot_name: "xtion"
  #  type: "transform"
  #  channel: "GT_CAMERA_OFFSET"


dynamics:
  dynamics_floating_base_var: 0.001 # m per frame
  dynamics_other_var: 0.001 # rad per frame
  verbose: True
  # and robot-specific additional gains:
  robot_specific_vars:
    - robot: "IRB140"
      dynamics_floating_base_var: 0.00000001 # m per frame
      dynamics_other_var: 0.01 # rad per frame
    - robot: "xtion"
      dynamics_floating_base_var: 0.000000001
      dynamics_other_var: 0.000000001
    - robot: "tiny_screwdriver"
      dynamics_floating_base_var: 0.0001
      dynamics_other_var: 0.0001
    #- robot: "bolt"
    #  dynamics_floating_base_var: 0.001
    #  dynamics_other_var: 0.001

costs:
 # - type: "NonpenetratingObjectCost"
 #   nonpenetration_var: 0.01 # m
 #   min_considered_penetration_distance: 0.001
 #   verbose: False
 #   verbose_lcmgl: False
 #   num_surface_pts: 200
 #   nonpenetrating_robot: "bolt"
 #   penetrable_robots: ["hole_box"]
 # - type: "NonpenetratingObjectCost"
 #   nonpenetration_var: 0.01 # m
 #   min_considered_penetration_distance: 0.001
 #   verbose: False
 #   verbose_lcmgl: False
 #   num_surface_pts: 200
 #   nonpenetrating_robot: "hole_box"
 #   penetrable_robots: ["bolt"]
  - type: "NonpenetratingObjectCost"
    nonpenetration_var: 0.001 # m
    min_considered_penetration_distance: 0.001
    verbose: True
    verbose_lcmgl: True
    num_surface_pts: 200
    nonpenetrating_robot: "tiny_screwdriver"
    penetrable_robots: ["hole_box"]

  - type: "KinectFrameCost"
    config: "/software/config/irb140/irb140.cfg"
    icp_var: 0.02 # m
    free_space_var: 0.05
    max_considered_icp_distance: 0.01
    min_considered_joint_distance: 0.03
    verbose: True
    verbose_lcmgl: True
    downsample_amount: 5.0
    #camera_body: "xtion"
    world_frame: True
    bounds:
      xMin: 0.43
      xMax: 0.67
      yMin: 0.03
      yMax: 0.17
      zMin: 0.7
      zMax: 1.0

 # - type: "GelsightCost"
 #   max_considered_corresp_distance: 0.03
 #   min_considered_penetration_distance: 0.001
 #   gelsight_depth_var: 0.001
 #   gelsight_freespace_var: 0.001
 #   timeout_time: 0.2
 #   contact_threshold: 0.1
 #   verbose: True
 #   surface:
 #     body: "wsg_50_finger_right_link"
 #     lower_left:  [-0.0189,0.0862, -0.0061]
 #     lower_right: [-0.0189,0.1129, -0.0061]
 #     upper_left:  [0.0078, 0.0862, -0.0061]
 #     upper_right: [0.0078, 0.1129, -0.0061]
 #     normal: [0.0, 0.0, -1.0]
 #     thickness: 0.002 # 5mm

#  - type: "AttachedApriltagCost"
#    verbose: false
#    verbose_lcmgl: true
#    timeout_time: 0.2
#    localization_var: 0.01
#    transform_var: .inf
#    world_frame: true
#    attached_manipuland: "IRB140_ATI_GELSIGHT"
#    apriltags:
#      - id: 100
#        body: "base_link"
#        pos: [0.175, 0.000, -0.086]
#        rot: [-90.574, -0.363, 89.095]
#        channel: APRIL_TAG_0100_TO_CAMERA_LEFT
#      - id: 101
#        body: "base_link"
#        pos: [0.171, 0.184, -0.082]
#        rot: [-89.101, -0.363, 89.095]
#        channel: APRIL_TAG_0101_TO_CAMERA_LEFT
#      - id: 102
#        body: "base_link"
#        pos: [0.171, 0.380, -0.066]
#        rot: [-89.101, -0.363, 89.095]
#        channel: APRIL_TAG_0102_TO_CAMERA_LEFT
#      - id: 50
#        body: "base_link"
#        pos: [0.819, -0.057, -0.197]
#        rot: [180.0, 0.0, 90.0]
#        channel: APRIL_TAG_0052_TO_CAMERA_LEFT
#      #- id: 52
#      #  body: "link_2"
#      #  pos: [-0.003, -0.356, -0.187]
#      #  rot: [0.722, -1.624, -67.355]
#      #  channel: APRIL_TAG_0052_TO_CAMERA_LEFT
#      - id: 51
#        body: "link_4"
#        pos: [0.154, -0.0, -0.064]
#        rot: [0.162, 1.477, -23.848]
#        channel: APRIL_TAG_0051_TO_CAMERA_LEFT

  - type: "RobotStateCost"
    joint_known_fb_var: 0.0000001 # m
    joint_known_encoder_var: 0.000001 # radian
    transcribe_floating_base_vars: False
    verbose: False
    state_channelname: "EST_ROBOT_STATE"