robots:
  irb140:
    urdf: "/software/models/IRB140/urdf/irb_140_ati_schunk_gelsight.urdf"
    q0:
      base_x: -0.17
      base_z: 0.91

  bolt:
    urdf: "/software/perception/manipulation_tracking/urdf/tiny_bolt.urdf"
    q0:
      base_x: 0.65
      base_y: 0.10
      base_z: 0.70
      base_roll: 0.0

  desk:
    urdf: "/software/perception/manipulation_tracking/urdf/desk.urdf"
    q0:
      base_x: 0.61
      base_y: 0.2
      base_z: 0.65

robots_less_collision:
  irb140:
    urdf: "/software/models/IRB140/urdf/irb_140_ati_schunk_gelsight_less_collision.urdf"
    q0:
      base_x: -0.17
      base_z: 0.91

  bolt:
    urdf: "/software/perception/manipulation_tracking/urdf/tiny_bolt.urdf"
    q0:
      base_x: 0.65
      base_y: 0.10
      base_z: 0.70
      base_roll: 0.0
  desk:
    urdf: "/software/perception/manipulation_tracking/urdf/desk.urdf"
    q0:
      base_x: 0.61
      base_y: 0.2
      base_z: 0.71

#post_transform:
#  source_robot: "IRB140_ATI_GELSIGHT"
#  dest_frame: "robot_base"

publish:
  irb140_state:
    robot_name: "IRB140"
    type: "state"
    channel: "EST_MANIPULAND_STATE_IRB140_ATI_GELSIGHT"
  tiny_bolt_state:
    robot_name: "bolt"
    type: "state"
    channel: "EST_MANIPULAND_STATE_bolt"
  desk_state:
    robot_name: "desk"
    type: "state"
    channel: "EST_MANIPULAND_STATE_desk"

dynamics:
  dynamics_floating_base_var: 0 # m per frame
  dynamics_other_var: 0.01 # rad per frame
  verbose: False

costs:
  - type: "KinectFrameCost"
    config: "/software/config/irb140/irb140.cfg"
    icp_var: 0.02 # m
    free_space_var: 0.05
    max_considered_icp_distance: 0.05
    min_considered_joint_distance: 0.03
    verbose: False
    verbose_lcmgl: True
    world_frame: True
    downsample_amount: 5.0
    bounds:
      xMin: 0.4
      xMax: 0.9
      yMin: 0
      yMax: 0.5
      zMin: 0.7
      zMax: 1.1

  - type: "GelsightCost"
    max_considered_corresp_distance: 0.03
    min_considered_penetration_distance: 0.001
    gelsight_depth_var: 0.002
    gelsight_freespace_var: 0.001
    timeout_time: 0.2
    contact_threshold: 0.1
    verbose: True
    surface:

      body: "wsg_50_finger_right_link"
      lower_left:  [-0.0189,0.0862, -0.0061]
      lower_right: [-0.0189,0.1129, -0.0061]
      upper_left:  [0.0078, 0.0862, -0.0061]
      upper_right: [0.0078, 0.1129, -0.0061]
      normal: [0.0, 0.0, -1.0]
      thickness: 0.002 # 5mm

#  - type: "AttachedApriltagCost"
#    verbose: false
#    verbose_lcmgl: true
#    timeout_time: 0.2
#    localization_var: 0.01
#    transform_var: .inf
#    world_frame: true
#    attached_manipuland: "IRB140_ATI_GELSIGHT"
#    apriltags:
#      - id: 100
#        body: "base_link"
#        pos: [0.175, 0.000, -0.086]
#        rot: [-90.574, -0.363, 89.095]
#        channel: APRIL_TAG_0100_TO_CAMERA_LEFT
#      - id: 101
#        body: "base_link"
#        pos: [0.171, 0.184, -0.082]
#        rot: [-89.101, -0.363, 89.095]
#        channel: APRIL_TAG_0101_TO_CAMERA_LEFT
#      - id: 102
#        body: "base_link"
#        pos: [0.171, 0.380, -0.066]
#        rot: [-89.101, -0.363, 89.095]
#        channel: APRIL_TAG_0102_TO_CAMERA_LEFT
#      - id: 50
#        body: "base_link"
#        pos: [0.819, -0.057, -0.197]
#        rot: [180.0, 0.0, 90.0]
#        channel: APRIL_TAG_0052_TO_CAMERA_LEFT
#      #- id: 52
#      #  body: "link_2"
#      #  pos: [-0.003, -0.356, -0.187]
#      #  rot: [0.722, -1.624, -67.355]
#      #  channel: APRIL_TAG_0052_TO_CAMERA_LEFT
#      - id: 51
#        body: "link_4"
#        pos: [0.154, -0.0, -0.064]
#        rot: [0.162, 1.477, -23.848]
#        channel: APRIL_TAG_0051_TO_CAMERA_LEFT

  - type: "RobotStateCost"
    joint_known_fb_var: 0.01 # m
    joint_known_encoder_var: 0.001 # radian
    transcribe_floating_base_vars: False
    verbose: False
    state_channelname: "EST_ROBOT_STATE"