robots:
  optotrak_cube:
    urdf: "/software/perception/manipulation_tracking/urdf/optotrak_cube.urdf"
    q0:
      base_x: 0.6
      base_z: 1.0
  irb140:
    urdf: "/software/perception/manipulation_tracking/urdf/irb140_chull_ati_gelsight.urdf"
    q0:
      base_x: -0.17
      base_z: 0.91


publish:
  irb140_state:
    robot_name: "IRB140_ATI_GELSIGHT"
    type: "state"
    channel: "EST_MANIPULAND_STATE_IRB140_ATI_GELSIGHT_GT"
  optotrak_cube_state:
    robot_name: "optotrak_cube"
    type: "state"
    channel: "EST_MANIPULAND_STATE_optotrak_cube_GT"

post_transform:
  source_robot: "IRB140_ATI_GELSIGHT"
  dest_frame: "robot_base"

dynamics:
  dynamics_floating_base_var: 0.01 # m per frame
  dynamics_other_var: 0.1 # rad per frame
  verbose: False

costs:
  - type: "OptotrakMarkerCost"
    verbose: false
    verbose_lcmgl: true
    timeout_time: 0.2
    localization_var: 0.001
    transform_var: .inf
    world_frame: true
    attached_manipuland: "optotrak_cube"
    markers:
# all units mm
# x width: 132.4
# y width: 126.1
# z widht: 126.1
# no markers on +x, -x surfaces, which are plates screwed onto box
#   12.4mm in from +x, -x surfaces
#   9.4mm in from the other direction
# origin is at the middle, so all markers are at x = +/- 53.8mm
#                                     +/- 63.05mm in the normal direction
#                                 and +/- 53.65mm in other dir
      - ids: [1]
        body: "optotrak_cube"
        pos: [-0.05380, -0.05365,  0.06305]
      - ids: [2]
        body: "optotrak_cube"
        pos: [ 0.05380, -0.05365,  0.06305]
      - ids: [3]
        body: "optotrak_cube"
        pos: [ 0.05380,  0.05365,  0.06305]
      - ids: [4]
        body: "optotrak_cube"
        pos: [-0.05380,  0.05365,  0.06305]
      - ids: [5]
        body: "optotrak_cube"
        pos: [-0.05380,  0.06305,  0.05365]
      - ids: [6]
        body: "optotrak_cube"
        pos: [ 0.05380,  0.06305,  0.05365]
      - ids: [7]
        body: "optotrak_cube"
        pos: [ 0.05380,  0.06305, -0.05365]
      - ids: [8]
        body: "optotrak_cube"
        pos: [-0.05380,  0.06305, -0.05365]
      - ids: [9]
        body: "optotrak_cube"
        pos: [-0.05380,  0.05365, -0.06305]
      - ids: [10]
        body: "optotrak_cube"
        pos: [ 0.05380,  0.05365, -0.06305]
      - ids: [11]
        body: "optotrak_cube"
        pos: [ 0.05380, -0.05365, -0.06305]
      - ids: [12]
        body: "optotrak_cube"
        pos: [-0.05380, -0.05365, -0.06305]
      - ids: [13]
        body: "optotrak_cube"
        pos: [-0.05380, -0.06305, -0.05365]
      - ids: [14]
        body: "optotrak_cube"
        pos: [ 0.05380, -0.06305, -0.05365]
      - ids: [15]
        body: "optotrak_cube"
        pos: [ 0.05380, -0.06305,  0.05365]
      - ids: [16]
        body: "optotrak_cube"
        pos: [-0.05380, -0.06305,  0.05365]

  - type: "OptotrakMarkerCost"
    verbose: false
    verbose_lcmgl: true
    timeout_time: 0.2
    localization_var: 0.001
    transform_var: .inf
    attached_manipuland: "IRB140_ATI_GELSIGHT"
    markers:
      - ids: [17, 18, 19]
        body: "link_1"
        pos: [0.07, -0.242, 0.204]
      - ids: [20, 21, 22]
        body: "link_3"
        pos: [0.099, 0.078, 0.074]
      - ids: [23, 24, 25]
        body: "link_4"
        pos: [0.161, 0.001, 0.070]

  - type: "RobotStateCost"
    joint_known_fb_var: .inf # m
    joint_known_encoder_var: 0.001 # radian
    transcribe_floating_base_vars: False
    verbose: False
    state_channelname: "EST_ROBOT_STATE"